---
language: go
go:
- tip
- 1.11.x
- 1.10.x
- 1.9.x
- 1.8.x
sudo: false

env:
  global:
  - GO111MODULE=on

# Forks will use that path for checkout
go_import_path: github.com/dolmen-go/endian

before_install:
- go list # Verify that go_import_path is ok
# Fetch dependencies:
# - go < 1.11:  go get -t -v ./...
# - go >= 1.11: go list -test
- "case \"$(go version)\" in (*' go1.'[0-9]*|*' go1.10.'*) go get -t -v ./... ;; (*) go list -test ;; esac"

script:
- go test -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
