// Code generated by generate_go1.17.go; DO NOT EDIT.

//go:build arm64be || armbe || mips || mips64 || ppc || ppc64 || s390 || s390x || sparc || sparc64
// +build arm64be armbe mips mips64 ppc ppc64 s390 s390x sparc sparc64

package endian

import "encoding/binary"

// Native is the byte order of GOARCH.
var Native = binary.BigEndian
