// Code generated by generate.go; DO NOT EDIT.

//go:build (arm64be || armbe || mips || mips64 || ppc || ppc64 || s390 || s390x || sparc || sparc64) && !generate && !endian_nostatic
// +build arm64be armbe mips mips64 ppc ppc64 s390 s390x sparc sparc64
// +build !generate
// +build !endian_nostatic

package endian

import "encoding/binary"

// Native is the byte order of GOARCH.
var Native = binary.BigEndian
