// Code generated by generate.go; DO NOT EDIT.

// +build 386 amd64 amd64p32 arm arm64 mips64le mipsle ppc64le riscv64 wasm

package endian

import "encoding/binary"

// Native is the byte order of GOARCH.
var Native = binary.LittleEndian
